### ISSUE TITLE
Plotting Reconstruction in Spyder

### ISSUE THREAD

**Issue by AnnieStephenson** [manoharan-lab/holopy#127]
In spyder, when we run:

zstack = np.linspace(1, 15, 8)
rec_vol = hp.propagate(holo, zstack)
hp.show(rec_vol)

It only shows one slice instead of 8. We cannot use the arrows to switch between the images. When we try to specify showing just one of the images, it gives an error.

**Comment by barkls** [comment]
plotting multiple z stacks works well in ipython, ok in jupyter, not at all in spyder. We need to test across different python platforms.

**Comment by barkls** [comment]
probably one the the following will work:

%matplotlib tk
%matplotlib qt
%matplotlib gtk

@AnnieStephenson can you try this out?

**Comment by barkls** [comment]
In Jupyter, you can get interactive plots by doing:

%matplotlib nbagg

**Comment by AnnieStephenson** [comment]
These commands cause a syntax error. A manual fix I found is to go to Tools > Preferences, then IPython console in the list of categories on the left, then the tab Graphics at the top, and change the Graphics backend to Qt.

**Comment by barkls** [comment]
%matplotlib commands work with the caveat that you can only have one matplotlib backend per ipython kernel. This has the following repercussions:

-You must use %matplotlib before using hp.show(), since spyder chooses a backend for you when you use hp.show() 

- If you try to set a backend that isn't installed, you cannot subsequently set to a new one, but have to restart the kernel.

- nbagg correctly interprets use of arrow keys inline in a jupyter notebook.
