### ISSUE TITLE
Optical train modeling

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#13]
We should be modeling the optical train more explicitly. This may help solve alpha, and could allow us to correct for things like tilt, spherical abberation and things of that sort.

**Comment by briandleahy** [comment]
This is now (partially) captured by the work @ralex0 and I have in the 3.3 release (cf #245, 250), in the ```Mielens``` theory. 

Right only the objective lens is modeled only for spheres, not for generic scatterers. However in the upcoming paper that @ralex0 and I are writing, we do lay out a way (in principle) to account for the objective lens for an arbitrary scatterer. I don't want to close this issue because generic scatterers aren't implemented yet, but I will say that I don't know if generic scatterers are feasible to implement numerically (the computation requirements might be too high). 

Thoughts? Do we keep this issue around or close it?

**Comment by vnmanoharan** [comment]
I think we keep it open -- not because we don't have an implementation for generic scatterers, but because we haven't yet modeled spherical aberration.

**Comment by briandleahy** [comment]
This is further addressed by #386 and #333 . 

In the future, one could add arbitrary aberrations, but for now I will close the issue.
