### ISSUE TITLE
Re-enable Internal Fields

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#144]
We have currently lost calculation of internal fields. I don't think they are extensively used, so I think we are going to release 3.0 without them, but it would be good to port that code from 2.x to the 3 version at some point.

**Comment by briandleahy** [comment]
It seems to me that the Mielens theory in 3.3 and the Lens() theory in #333 render this issue a moot point, since when the focal plane is inside the particle someone really should be using a theory which describes the effect of the lens. 

So I'm closing this issue; please re-open it if there is a use case for internal fields that I'm not aware of.
