### ISSUE TITLE
Inconsistency between prior.Gaussian and prior.Uniform

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#153]
Currently, priors are specified as follows:

prior.Gaussian(mean, width)
prior.Uniform(lower_bound, upper_bound)

I propose changing prior.Uniform to take the same arguments as prior.Gaussian:
prior.Uniform(mean, width)

Was this inconsistency intentional to emphasize that these two priors are distinct?

**Comment by tdimiduk** [comment]
They are specified that way because those are the terms you think about
when defining the priors. That is how things are done in the math, at least
as far as I have seen, so I think the inconsistency here is less important
than staying consistent with standard usage of the priors.

Uniform has some known region in which the probability is nonzero, but
knows nothing more. If you know a point and some distribution around that
point, you would tend to use a gaussian instead of a uniform.
