### ISSUE TITLE
Janus Particles

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#204]
The current HoloPy Janus implementation is a sphere with an outer shell of uniform thickness over half of the sphere. Anna has a separate implementation of a JanusCrescent with description:

>         A two layer particle with the outer layer only spanning one hemisphere and tapering
>        off as it nears the edges of the particle. This is to mimic a particle that has had
>        a thin layer sputtered onto it, with directional sputtering. 

Anna's JanusCrescent is not currently incorporated into HoloPy. Do we want to include it? If so, should it replace the current Janus sphere or be in addition to it?

**Comment by vnmanoharan** [comment]
I think we should include JanusCrescent, if that is what we used for the DDA paper. I want to clean up and release all the code that has been used in our publications. @anna-wang, can you confirm that this is the scatterer you used in the DDA paper?  Did you ever use the other Janus implementation?

**Comment by anna-wang** [comment]
Hi Vinny - I only used Janus crescent, not the Janus sphere. I have
modified Janus crescent, spheroid, and capped cylinder to work with the
newest version of HoloPy. These are the three I have used in publications.

Anna

On 29 Jul. 2017 12:18 pm, "vnmanoharan" <notifications@github.com> wrote:

I think we should include JanusCrescent, if that is what we used for the
DDA paper. I want to clean up and release all the code that has been used
in our publications. @anna-wang <https://github.com/anna-wang>, can you
confirm that this is the scatterer you used in the DDA paper? Did you ever
use the other Janus implementation?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/manoharan-lab/holopy/issues/204#issuecomment-318841452>,
or mute the thread

**Comment by barkls** [comment]
If the existing JanusSphere was not used, are we ok replacing it with Anna's version (and renaming it JanusSphere)?

**Comment by vnmanoharan** [comment]
I would keep JanusSphere, but it should be better documented.  It is difficult to determine what the exact structure is from the constructive solid geometry in indicators().

**Comment by barkls** [comment]
I moved both Janus descriptions into a single file, Janus.py, which now contains two classes: ``JanusSphere_Uniform`` and ``JanusSphere_Tapered``. It might have been better to make them a single class with an argument to choose between  the two methods, but I though it was more clear to have them as completely separate classes.
