### ISSUE TITLE
OME Tiff stack - process as timeseries?

### ISSUE THREAD

**Issue by rbnvrw** [manoharan-lab/holopy#217]
I am using data collected using [MicroManager](https://micro-manager.org/) which saves its videos as [.ome.tiff files](https://docs.openmicroscopy.org/ome-model/5.6.1/ome-tiff/).

I would like to analyse the hologram using the Bayesian inference method as described in the manual. However, when I try to load the file using `hp.load_image()` I get the following shape: `(z: 1, x: 2048, y: 2048)`. Obviously it only loads the first frame of the tiff file.

I can however easily load the tiff series using [PIMS](http://soft-matter.github.io/pims/v0.4/). Is it maybe possible to either:

1. Open the tiff series with a HoloPy function
2. Use the data from PIMS (which are decorated NumPy arrays) in the HoloPy functions (`bg_correct`, `normalize`, `tempered_sample`)

Thank you for your efforts.

**Comment by barkls** [comment]
As you discovered, HoloPy cannot currently load all the frames of a multi-image .tiff file. While this wouldn't be hard to implement, it might not be very useful because the rest of HoloPy assumes you are working with a single frame. ``normalize`` and ``bg_correct`` haven't been tested with multidimensional images and may or may not behave as expected. More specifically the ``AlphaModel`` used in inferences assumes you are calculating a single hologram. I see two possible solutions for you:

1) Use single images only. Since you can load the data with PIMS, you can convert individual frames into data structures HoloPy will recognize using ``hp.core.metadata.data_grid``. This isn't normally a user-facing function so let me know if you run into difficulties.

2) Use full timeseries data. You will need to write a new ``NoiseModel`` subclass for time-series data to replace ``AlphaModel``. This is something we would like to incorporate into HoloPy eventually, so I am happy to help get you started if you want to follow this route.

**Comment by rbnvrw** [comment]
Thank you for the clear reply, I will try to look into option 2 and contact you if I cannot figure it out.

**Comment by tdimiduk** [comment]
It is probably also worth looking at making PIMS image loading into a first
class citizen in HoloPy. HoloPy predates PIMS (or at least my awareness of
PIMS), but if I was building it today I would probably use PIMS
infrastructure for a lot of the image loading. I think I got part way
through implementing a HoloPy PIMS layer before we switched to xarray and
HDF5.

I don't have a clear picture what the mismatch between PIMS's decorated
NumPy arrays and HoloPy's DataArrays are anymore, but I think it might be a
fairly simple adapter, and would be a welcome addition to HoloPy if you are
able to write it. It would also be a good first step towards Solomon's
option (2) in that it would let you easily get the whole timeseries into
HoloPy. You will probably end up basically wanting to follow Solomon's (1)
and use data_grid as inspiration for a function that will pull in the PIMS
data, convert it to a DataArray and add HoloPy needed metadata.

**Comment by tdimiduk** [comment]
Right, I PIMS's lazy loading model, while useful for some things, is a
pretty serious mismatch with the way that is easiest with xarray, and we
get better lazy loading functionality with HDF5 files. Now I remember why I
aborted the PIMS project, thanks for the reminder.

**Comment by barkls** [comment]
Ok @rbnvrw , I've created a [new branch](https://github.com/manoharan-lab/holopy/tree/timeseries) that lets you load tiff-stacks as a timeseries using ``hp.load_image``. I haven't tested any other HoloPy functions on the resulting 4-dimensional DataArrays (including a singleton z-dimension). Let me know how it goes!

**Comment by rbnvrw** [comment]
I've done some quick tests, but for my data I really need the lazy loading functionality (the timeseries are ~5GB per file).

I guess it would be best to first convert the tiff stack to a HDF5 file and then load it in HoloPy, as HoloPy supports lazy loading of the HDF5 files?

**Comment by tdimiduk** [comment]
Yes, if you can convert to hdf5 that will likely give you better
performance since hdf5 is a better designed format for these kinds of
access. If that doesn't work or make sense then you will want to explore to
convert the lazy loaded frames into HoloPu images on the fly

**Comment by rbnvrw** [comment]
Update: I decided to go the route of converting the lazy loaded frames into HoloPy images on the fly.

I tried the hdf5 approach, but almost all HoloPy functions I wanted to use didn't work with image stacks (bg_correct and all the fit functions) so I think it is not feasible without adapting a large part of the code.

**Comment by barkls** [comment]
I was afraid this might be the case. Hopefully we will get HoloPy to support multidimensional images soon!

**Comment by barkls** [comment]
Closing this issue. Any further discussion should be directed to #46.
