### ISSUE TITLE
Is this output correct?

### ISSUE THREAD

**Issue by squeakus** [manoharan-lab/holopy#319]
Hi,
I am working through the tutorial and I have  a reconstruction of the example data. It gave a warning

vis.py:188: UserWarning: Image contains complex values. Taking image magnitude.
warn("Image contains complex values. Taking image magnitude.")

Is this what the result should look like? It basically looks like a brighter version of the raw image.

https://imgur.com/a/zYAxfnd

**Comment by briandleahy** [comment]
Thanks for pointing this out @squeakus . Can you quickly say which line in the tutorial you were running?

Thanks!

**Comment by squeakus** [comment]
Apologies I should have added that. I am working from this tutorial:
https://holopy.readthedocs.io/en/stable/users/recon_tutorial.html#example-reconstruction
imagepath = get_example_data_path('image01.jpg')
raw_holo = hp.load_image(imagepath, spacing = 0.0851, medium_index = 1.33, illum_wavelen = 0.66, )
bgpath = get_example_data_path(['bg01.jpg','bg02.jpg','bg03.jpg'])
bg = load_average(bgpath, refimg = raw_holo)
holo = bg_correct(raw_holo, bg)

zstack = np.linspace(0, 20, 11)
rec_vol = hp.propagate(holo, zstack)
hp.show(rec_vol)

**Comment by barkls** [comment]
Hi @squeakus, that code actually returns a stack of images, representing a 3D volume of slices at different reconstruction distances above the focal plane. You should be able to navigate through them wiht left and right arrow keys. 

There's a [quick diagnostic test](https://holopy.readthedocs.io/en/stable/users/install.html#using-holopy) to make sure everything's working as intended on the display side of things.

The first image in the stack corresponds to a reconstruction distance of 0 (since that's the first element of `zstack`, so it should look exactly the same as  the raw image.

**Comment by squeakus** [comment]
ahh, I have set it up to run with QT and now I can see the different images
in the stack, thanks!
