### ISSUE TITLE
Make Mie automatically determine if it needs to compute near field stuff

### ISSUE THREAD

**Issue by tdimiduk** [manoharan-lab/holopy#34]
Using compute_escat_radial and full_radial_dependence in Mie calculations when you don't need to can cost almost a factor of 10 in run time in some cases. I think it should be possible to pick a conservative threshold where they are definitely not needed and have the code automatically turn those extra calculations off.

**Comment by barkls** [comment]
@jeromefung do you know how far away from the particle the near-field effects are significant?

**Comment by jeromefung** [comment]
I'd have to look at my notes for details, but basically you need 1/(kz) to
be small because the radial dependence can be expanded in a series in
powers of 1/kr. Back-of-the envelope calculations for water and a 660 nm
laser give kz ~ 130 for z = 10 microns, at which point 1/kz is small but
higher-order contributions are not entirely negligible. Since we typically
operate at z ranging from several microns to several 10s of microns, the
default has been to model the full radial dependence.

I'm not sure if anyone ever did systematic, detailed studies of how far out
one in practice needs to go before the asymptotic limit is valid; almost
certainly not if kz < 100. I think in practice not including the full
radial dependence leads to an offset in the fitted value of z. But how much
one cares probably depends on the experiment -- in some cases a systematic
offset in fitted z values might not matter.

Jerome

**Comment by barkls** [comment]
From Jerome's details it looks like we nearly always need the full calculation, so this isn't relevant.
