### ISSUE TITLE
Hologram generation and reconstruction for large scatterers 

### ISSUE THREAD

**Issue by arthudubois** [manoharan-lab/holopy#363]
Hi, 
I'm trying to generates holograms and reconstructions for one sphere with a radius ~50 µm. My detector is shape = (200, 200), spacing = 5. The hologram with a sphere at (500, 500, 500) looks like this with illumination at  0.532µm : 
![Figure_1](https://user-images.githubusercontent.com/59050347/89506207-12163680-d7cb-11ea-9f5e-994509648534.png)
But the reconstruction with zstack = np.linspace(250, 750, 201) seems strange : 
![Figure_2](https://user-images.githubusercontent.com/59050347/89506959-2ad31c00-d7cc-11ea-8e3a-fe67d7039853.png)
![Figure_2_500](https://user-images.githubusercontent.com/59050347/89506966-2c9cdf80-d7cc-11ea-873b-5277990ee3a2.png)
![Figure_2_700](https://user-images.githubusercontent.com/59050347/89506983-31619380-d7cc-11ea-9766-89d5d1a371fe.png)
It seems that the reconstructed slices are all the same.

For small particles the results seem corrects but starting from 5µm radius the reconstructions are strange, like above

**Comment by briandleahy** [comment]
Hi @arthudubois ,

Well, the calculations may be problematic, but at least they make beautiful images!! :smile:

I think you are seeing aliasing, from the large pixel spacing on your detector. If I run:

```python
from holopy.scattering import Sphere, Mie, calc_holo
from holopy import detector_grid 

sphere = Sphere(center=(500, 500, 500), n=1.59, r=50)
detector = detector_grid(shape=(200, 200), spacing=5.0)

holo = calc_holo(
    detector, sphere, medium_index=1.33, illum_wavelen=0.532,
    illum_polarization=(1, 0))
```
then I get basically the exact same plot you had above. But if I zoom in by a factor of 10, calculating at more pixels, like so,
```python
detector_zoom = detector_grid(shape=(200, 200), spacing=0.50)          
sphere_zoom = Sphere(center=(50, 50, 500), n=1.59, r=50)               

holo_zoom = calc_holo(
    detector_zoom, sphere_zoom, medium_index=1.33,
    illum_wavelen=0.532, llum_polarization=(1, 0))
```
then I get this much more reasonable image:

![zoomed-hologram](https://user-images.githubusercontent.com/25911342/89581665-5aeae100-d805-11ea-9d2d-dadd9f686704.png)

The problem with your original image is that your pixel sampling density is far too low to see the structure in the hologram, so you just see the aliasing effect. Doing a reconstruction likewise fails because input to the reconstruction calculation isn't sampled densely enough.

If you do want to reconstruct, I would calculate the hologram at a much higher pixel density (something like 0.5 um / pixel). This will take a long time; be forewarned.

As an aside, 
* Most of the calculations we do with holopy is with smaller spheres. So you might run into numerical issues when the sphere is big. The Mie theory code throws an error if the radius is too large, but there could be some instabilities for spheres near that value, which you might see in addition to aliasing.
* If you want to calculate holograms for spheres in the 10 um range, it might be faster to use the MieLens theory rather than Mie theory. The MieLens theory includes the effects of a perfect lens on the recorded hologram, but it also uses some numerical tricks to calculate holograms faster. As a result, on my machine the MieLens theory is 32x faster than the Mie theory on the 200x200 pixel grids with 5.0 micron spacing that you are using. That being said, right now numerical instabilities cause the MieLens code to crash when the size parameter is greater than ~10, so it won't work for your 50 um spheres. 

Let me know if that helped,

**Comment by arthudubois** [comment]
Hi @briandleahy 
Thanks a lot for your help.
Generation with a x10 zoom works perfectly but the reconstruction is still strange.
I tried to increase pixel density and got this result : 
``` Python
from holopy.scattering import Sphere, Mie, calc_holo
from holopy import detector_grid 
import numpy as np

sphere = Sphere(center=(50, 00, 500), n=1.4, r=50)
detector = detector_grid(shape=(1000, 1000), spacing=.1)

holo = calc_holo(
    detector, sphere, medium_index=1.0, illum_wavelen=0.532,
    illum_polarization=(1, 0))
zstack = np.linspace(250, 750, 201)
rec_vol = hp.propagate(holo, zstack, medium_index=1.0, illumin_wavelen=0.532)
```
![Figure_10_250](https://user-images.githubusercontent.com/59050347/89655348-43c1f700-d8ca-11ea-8872-6557e11706e8.png)
![Figure_10_410](https://user-images.githubusercontent.com/59050347/89655354-44f32400-d8ca-11ea-890c-eb22edc08c55.png)
![Figure_10_500](https://user-images.githubusercontent.com/59050347/89655333-402e7000-d8ca-11ea-85a1-758c408c6a3f.png)
![Figure_10_600](https://user-images.githubusercontent.com/59050347/89655338-41f83380-d8ca-11ea-858f-374188c79f2a.png)
Is the pixel density still to low ?


For the Mie theory I manage generate hologram with sphere up to 83 µm radius (if I remember correctly) without getting an error.

**Comment by barkls** [comment]
Reconstruction tries to propagate the field back into various planes, but it doesn't know what the field is outside the image. This introduces artifacts in reconstructions that move inwards from the edges of the image to the center with increasing z-propagation distance. Usually the solution is to make sure the image you are reconstructing includes a large enough buffer region between the hologram of interest and the edge of the image. Here you would need to have both a high pixel density and a very large extent of the image to get reasonable reconstructions, so the computation time and memory load might be prohibitively expensive for spheres this large.
