### ISSUE TITLE
Propagate/Detrend

### ISSUE THREAD

**Issue by VitanPy** [manoharan-lab/holopy#410]
Hi all,

First question: how do I use 'propagate' to estimate the z distance of a scatterer from a hologram?

Second: Detrend produces a value error when used on the example holograms. The other functions from the same submodule do not. How do I fix this issue?

Vitan

**Comment by vnmanoharan** [comment]
For the first question, you can propagate to various distances, but you would need to have some criterion for determining when the reconstruction is in focus. There are many papers proposing different criteria (example: https://doi.org/10.1364/OE.14.005895)

For the second question, this is a bug.  Should be fixed in #436.  Thank you for reporting the error!
