### ISSUE TITLE
switch to xarray

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#45]
Pandas is currently used in the Bayesian inference code. We might as well expand it to the rest of holopy where it makes sense, for example timeseries data.

**Comment by vnmanoharan** [comment]
We should look into using [xarray](http://xarray.pydata.org/en/stable/why-xarray.html). Unlike pandas, it supports multidimensional data sets.  It also [supports metadata](http://xarray.pydata.org/en/stable/data-structures.html#dataarray) in that you can assign a dictionary containing the metadata to a data set. Finally, it is based on pandas, so that we would not have to rewrite the Bayesian inference code.  We might think about using it to replace Marray.

**Comment by tdimiduk** [comment]
Yes, it looks like xarray is going to be the right way to do things. I have a very solid proof of concept that it works in my xarray branch:
https://github.com/tdimiduk/holopy/tree/xarray

I looks like it will be able to replace Marray, and give a much cleaner way of handling things like electric field components and timeseries or z stacks. 

I should be submitting a PR soon.

**Comment by tdimiduk** [comment]
Backwards comparability question I would like @vnmanoharan's opinion on. 

xarray looks like it will make it possible to eliminate most of the marray classes and code. However, loading old yaml files needs those classes to exist. So far I see two decent ways of dealing with this:

1) Eliminate the code from holopy, provide a separate tool to convert old files into new hdf5/netcdf files

2) Keep the code in holopy but separate it off into a backwards compatibility file/directory so that holopy can still read all the old files directly, constructing new xarray objects for the user (which in turn can/should be saved as new hdf5/netcdf)

Opinions on which route to take, or do you want to propose a third option?

**Comment by vnmanoharan** [comment]
Spoke to @tdimiduk offline about this, but re-capping for the record: my preference is to get rid of the legacy code, since otherwise we'll have to maintain it, and to provide a separate tool to convert between formats.
