### ISSUE TITLE
hp.show doesn't work in python 3

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#77]
Installation of cairocffi doesn't resolve.

**Comment by ProfPh** [comment]
Using the `show` function directly from `matplotlib.pylab` fixed this issue for me. Prior to this, nothing would happen when `hp.show` was run.

**Comment by barkls** [comment]
Hi ProfPh,

This is a closed issue, and as far as we know, everything with ``hp.show`` is working as intended.

If you are encountering a problem, I would appreciate your help in tracking it down and resolving the issue. The holopy show function has some additional functionality on top of the matplotlib show function. Have you tried going through the steps to diagnose visualizations in our [documentation](http://holopy.readthedocs.io/en/3.1.1/users/install.html#using-holopy)?

**Comment by ProfPh** [comment]
Yes I have seen that page. Continuing from my previous comment, I found that using an empty `matplotlib.pylab.show` immediately afterward the `hp.show` is enough to show the image properly. This same behaviour can be recreated for `test_disp`. Looks like some kind of initialisation problem?

```
import holopy as hp
from holopy.core.io import get_example_data_path
from holopy.core.process import bg_correct
import matplotlib.pylab

imagepath = get_example_data_path('image01.jpg')
bgpath = get_example_data_path(['bg01.jpg', 'bg02.jpg', 'bg03.jpg'])
raw_holo = hp.load_image(imagepath, spacing = 0.0851)
bg = hp.core.io.load_average(bgpath, refimg = raw_holo)
holo = bg_correct(raw_holo, bg)
hp.show(holo)
matplotlib.pylab.show(holo)
```

This is on Anaconda 5.0.1 64bit, Python 3.6, HoloPy v3.0 (ralex0), matplotlib v2.0.2

**Comment by ProfPh** [comment]
Yes I have seen that page. Continuing from my previous comment, I found that using an empty `matplotlib.pylab.show` immediately afterward the `hp.show` is enough to show the image properly. This same behaviour can be recreated for `test_disp`. Looks like some kind of initialisation problem?

```
import holopy as hp
from holopy.core.io import get_example_data_path
from holopy.core.process import bg_correct
import matplotlib.pylab

imagepath = get_example_data_path('image01.jpg')
bgpath = get_example_data_path(['bg01.jpg', 'bg02.jpg', 'bg03.jpg'])
raw_holo = hp.load_image(imagepath, spacing = 0.0851)
bg = hp.core.io.load_average(bgpath, refimg = raw_holo)
holo = bg_correct(raw_holo, bg)
hp.show(holo) #this alone shows nothing and the script terminates without errors
matplotlib.pylab.show(holo)
```

This is on Anaconda 5.0.1 64bit, Python 3.6, HoloPy v3.0 (ralex0), matplotlib v2.0.2

**Comment by ProfPh** [comment]
Yes I have seen that page. Continuing from my previous comment, I found that using an empty `matplotlib.pylab.show` immediately afterward the `hp.show` is enough to show the image properly. This same behaviour can be recreated for `test_disp`. Looks like some kind of initialisation problem?

```
import holopy as hp
from holopy.core.io import get_example_data_path
from holopy.core.process import bg_correct
import matplotlib.pylab

imagepath = get_example_data_path('image01.jpg')
bgpath = get_example_data_path(['bg01.jpg', 'bg02.jpg', 'bg03.jpg'])
raw_holo = hp.load_image(imagepath, spacing = 0.0851)
bg = hp.core.io.load_average(bgpath, refimg = raw_holo)
holo = bg_correct(raw_holo, bg)
hp.show(holo) #this alone shows nothing and the script terminates without errors
matplotlib.pylab.show()
```

This is on Anaconda 5.0.1 64bit, Python 3.6, HoloPy v3.0 (ralex0), matplotlib v2.0.2

**Comment by barkls** [comment]
Great, thanks for the description. I'm not sure why that is happening, but I will add a note to the documentation in case others encounter the same behaviour.

**Comment by briandleahy** [comment]
Fixed by #291

**Comment by gorogm** [comment]
I still need this wrapping
```
import matplotlib.pylab
...
matplotlib.pylab.show()
```

to see the image when running the basic examples, otherwise nothing appears. Tested without jupyter, with latest holopy code, python 3.8.

**Comment by gorogm** [comment]
Also, I couldn't find the promised note in the documentation, would you like to add @barkls  ?

**Comment by briandleahy** [comment]
Hi @gorogm , 

Can you check the value of `matplotlib.rcParams['interactive']`?

**Comment by gorogm** [comment]
dear @briandleahy , it seems to be False (ubuntu, python 3.8.5)

**Comment by briandleahy** [comment]
Hi @gorogm ,

`hp.show` uses matplotlib to display images. matplotlib has an interactive mode or a non-interactive mode. For most use cases, matplotlib is launched with the interactive mode on, and calling `hp.show` will immediately show the hologram. If the interactive mdoe is off, however, then because hp.show just calls matplotlib functions, the hologram will not appear until an explicity `pyplot.show()` command is called.

I don't want to change `holopy` to automatically turn matplotlib's interactive plotting on, because this would stop people from using `hp.show` in scripts. (It's problematic to save hundreds of images in a script when figures keep showing up on your screen.) So I don't think we will change holopy to automatically show images when `hp.show` is called; I would rather respect the user's preferences. 

If you want the hologram to appear the moment `hp.show` is called, you can explicitly set matplotlib to be interactive. You can do this either by
* `import matplotlib.pyplot as plt; plt.ion()`, or
* setting `matplotlib.rcParams['interactive'] = True`
Doing either of those will make the hologram appear immediately after `hp.show` is called. Instead, you can also call `plt.show` when you want to see the hologram. With my personal workflow (using an ipython terminal or a jupyter notebook), matplotlib starts as interactive, so I don't have to do this. You can also change matplotlib's rcParams to be interactive by default if that is not already the case; see the matplotlib documentation.

Does that answer your question?

**Comment by gorogm** [comment]
thank you @briandleahy, it's all clear now! I was not aware of the 'interactive' flag of matplotlib and the fact that it's different with / without jupyter.
